### ISSUE TITLE
Hotel - Legal entity (0.5sp)

### ISSUE THREAD

**Issue by mikozza** [windingtree/wiki#87] opened 2019-02-06 21:29 UTC
I propose to create a new object for a legal entity which is in charge of hotel operation. This should include company name, VAT number, contact, and address.

https://github.com/windingtree/wiki/blob/ebf034be7464ebb1244ed77e97b08996d986da40/hotel-data-swagger.yaml#L69

**Comment by JirkaChadima** [comment] 2019-02-07 09:53
We definitely need to do this and ideally find an international data standard for this.

One thing that comes to mind is how this might be connected to hotel chains - do you have any knowledge how these work that you could share? Whether they are owned by the same company, international branches of the same company or as a franchise sharing only the name and license?

**Comment by mikozza** [comment] 2019-02-07 21:09
The legal entity should be the actual operator of the hotel.  Not the owner or the owner of the franchise or brand.

In other words, who is responsible for the hotel operation? If the stuff of the guest get stolen by hotel personnel, what company can be sued by a guest?

In the case of hotel chains, even though they can have various child companies etc. One company is always responsible for the operation...

**Comment by JirkaChadima** [comment] 2019-02-08 07:27
I see, thanks for the insight!

**Comment by czervenka** [comment] 2019-02-13 09:50
Let's add it to hotel data for now.

There is other approach to add legal entity to blockchain registry (so that any entity can manage it's own data).

**Comment by JirkaChadima** [comment] 2019-02-14 12:00
So, this is a fun area of research. To be able to cover the whole world, I think we need to store:

- `name` - legal company name
- `address` - postal address (existing WT address format, will get changed after #84 )
- `contact` - e-mail, phone, whatever... (existing contact format)
- VATIN - VAT identification number - this can be [VATIN](https://en.wikipedia.org/wiki/VAT_identification_number) in Europe, [TIN](https://www.irs.gov/individuals/international-taxpayers/taxpayer-identification-numbers-tin) in US and an equivalent in other regions
- LEI - [Legal Entity Identifier](https://en.wikipedia.org/wiki/Legal_Entity_Identifier) to be future-proof

In some cases, apart from VATIN, other identification numbers are/can be used, but I think that the VAT registration number should be enough. The problem is the non-uniformity of formats, so the validation is a) impossible b) really hard.

We should call this field `operator` and use it withing the airlines data model as well. Do you agree with this, @mikozza @czervenka ?

**Comment by czervenka** [comment] 2019-02-15 06:57
@JirkaChadima I'm OK with that. Just the word "operator" can be misleading sometimes as a hotel is not always operated by an owner so that operator and owner are two different legal entities.

@mikozza what do you think?

**Comment by JirkaChadima** [comment] 2019-02-15 06:59
That was the exact intention as @mikozza said in an earlier comment that we should have a legally responsible operator in the data.

**Comment by czervenka** [comment] 2019-02-15 07:27
I forgot. It's perfect then.

**Comment by JirkaChadima** [comment] 2019-02-15 12:19
I'll use this as a tracking issue:

In order to add support for this throughout the platform, we apart from #91 need to:

* [ ]   show support for this in wt-fixtures
* [ ]   bump swagger docs in wt-read-api + test support for this
* [ ]   bump swagger docs in wt-write-api + test support for this (maybe even do a validation for vatin/lei)
* [ ]   show these fields in the hotel explorer

Non critical

* [ ]   bump swagger docs in wt-search-api + test support for this

To keep in mind

* This uses the address type which is getting a revamp in #84 so we should release those two things at once to prevent double-work.

**Comment by JirkaChadima** [comment] 2019-02-22 09:46
This will land in the next release. Closing.

**Closed by JirkaChadima** 2019-02-22 09:46 UTC
Labels: data structure
